# Generated by Django 6.0 on 2025-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_city_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='max_guests',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
