# Generated by Django 6.0 on 2025-12-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '0005_alter_listing_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_request', to='listings.listing'),
        ),
    ]
